from .version import version as __version__

# Only needed for side effects
from . import _initialize
from .exceptions import HALError

# not autogenerated by 'robotpy-build create-imports hal hal._wpiHal'
from ._wpiHal import *
from ._wpiHal import __hal_simulation__

if __hal_simulation__:
    from ._wpiHal import (
        loadExtensions,
        loadOneExtension,
        setDutyCycleSimDevice,
        setShowExtensionsNotFoundMessages,
    )
