from . import _init__cscore

# autogenerated by 'semiwrap create-imports cscore cscore._cscore'
from ._cscore import (
    CameraServer,
    CvSink,
    CvSource,
    HttpCamera,
    ImageSink,
    ImageSource,
    MjpegServer,
    RawEvent,
    UsbCamera,
    UsbCameraInfo,
    VideoCamera,
    VideoEvent,
    VideoListener,
    VideoMode,
    VideoProperty,
    VideoSink,
    VideoSource,
    run_main_run_loop,
    run_main_run_loop_timeout,
    stop_main_run_loop,
)

__all__ = [
    "CameraServer",
    "CvSink",
    "CvSource",
    "HttpCamera",
    "ImageSink",
    "ImageSource",
    "MjpegServer",
    "RawEvent",
    "UsbCamera",
    "UsbCameraInfo",
    "VideoCamera",
    "VideoEvent",
    "VideoListener",
    "VideoMode",
    "VideoProperty",
    "VideoSink",
    "VideoSource",
    "run_main_run_loop",
    "run_main_run_loop_timeout",
    "stop_main_run_loop",
]

from ._logging import enable_logging

__all__.append("enable_logging")

try:
    from .version import __version__
except ImportError:
    __version__ = "master"
