import inspect

from ._cscore import CameraServer


def run(grip_pipeline):
    """
    A function that can be used to run python image processing code
    as generated by GRIP
    """

    if inspect.isclass(grip_pipeline):
        grip_pipeline = grip_pipeline()

    cs = CameraServer
    cs.enable_logging()

    cs.start_automatic_capture()
    cv_sink = cs.get_video()

    output_stream = None
    img = None

    while True:
        time, img = cv_sink.grab_frame(img)
        if time == 0:
            if output_stream:
                output_stream.notify_error(cv_sink.get_error())

            continue

        # Process it with GRIP
        out_img = grip_pipeline.process(img)
        if out_img is not None:
            try:
                output_stream.put_frame(out_img)
            except AttributeError:
                if output_stream is None:
                    output_stream = cs.put_video("GRIP", img.shape[1], img.shape[0])
                else:
                    raise
