"""
This package contains the WPILib Struct serialization functions, and a
mechanism to implement your own custom structs using Python (see :func:`wpiutil.wpistruct.make_wpistruct`).
"""

# autogenerated by 'robotpy-build create-imports wpiutil.wpistruct wpiutil._wpiutil.wpistruct'
from .._wpiutil.wpistruct import (
    forEachNested,
    getSchema,
    getSize,
    getTypeString,
    pack,
    packInto,
    unpack,
)

__all__ = [
    "forEachNested",
    "getSchema",
    "getSize",
    "getTypeString",
    "pack",
    "packInto",
    "unpack",
]

from .desc import StructDescriptor

from .dataclass import (
    make_wpistruct,
    int8,
    uint8,
    int16,
    uint16,
    int32,
    uint32,
    int64,
    uint64,
    double,
)

__all__ += [
    "StructDescriptor",
    "make_wpistruct",
    "int8",
    "uint8",
    "int16",
    "uint16",
    "int32",
    "uint32",
    "int64",
    "uint64",
    "double",
]
