# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2024.0.0b3.post2.dev3+g375e0468.d20231113'
__version_tuple__ = version_tuple = (2024, 0, 0, 'dev3', 'g375e0468.d20231113')
