from . import _init__interfaces

# autogenerated by 'semiwrap create-imports wpilib.interfaces wpilib.interfaces._interfaces'
from ._interfaces import CounterBase, GenericHID, MotorController

__all__ = ["CounterBase", "GenericHID", "MotorController"]

del _init__interfaces
